# Why Pandas?

- Flexibility of Python
- Works well with Big Data

# Loading Data into Pandas

In [7]:
#import pandas lib
import pandas as pd

In [133]:
# loading csv files

import pandas as pd
df = pd.read_csv('pokemon_data.txt') #the file extension can be .csv or .txt for the read_csv() method
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [13]:
#loading excel files

import pandas as pd
df_xlsx = pd.read_excel('pokemon_data.xlsx') #the file extension can be .csv or .txt for the read_csv() method
df_xlsx

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [20]:
# loading txt(tab separated files) files

import pandas as pd
df = pd.read_csv('pokemon_data (1).txt', delimiter='\t') #note the delimiter argument:since its a tab sep file, delimiter='\t'
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [16]:
# getting head and tail

df.head() #gives the first five rows

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [17]:
df.tail() #gives the last five rows

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [18]:
df.head(10) #we can also have a parameter within the parenthesis. This shows the first 10 rows

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,44,48,65,50,64,43,1,False

# Reading Data in Pandas

In [21]:
#Reading Headers

df.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [23]:
#Read specific Column

df[['Name']] #gives data in column Name. We used double [] so as not to print in series

                      Name
0                Bulbasaur
1                  Ivysaur
2                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
..                     ...
795                Diancie
796    DiancieMega Diancie
797    HoopaHoopa Confined
798     HoopaHoopa Unbound
799              Volcanion

[800 rows x 1 columns]

In [27]:
df['Name'][0:3] #prints first 3 rows

0    Bulbasaur
1      Ivysaur
2     Venusaur
Name: Name, dtype: object

In [29]:
#we can also do df.headers.NOTE: It doesnt go with 2 name headers like 'abc def' only 'abcdef' 

df.Name

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object

In [30]:
#reading multiple columns

df[['Name', 'Type 1', 'Type 2']]

                      Name   Type 1  Type 2
0                Bulbasaur    Grass  Poison
1                  Ivysaur    Grass  Poison
2                 Venusaur    Grass  Poison
3    VenusaurMega Venusaur    Grass  Poison
4               Charmander     Fire     NaN
..                     ...      ...     ...
795                Diancie     Rock   Fairy
796    DiancieMega Diancie     Rock   Fairy
797    HoopaHoopa Confined  Psychic   Ghost
798     HoopaHoopa Unbound  Psychic    Dark
799              Volcanion     Fire   Water

[800 rows x 3 columns]

In [32]:
#Read Each Row using iloc

df.iloc[0]

#                     1
Name          Bulbasaur
Type 1            Grass
Type 2           Poison
HP                   45
Attack               49
Defense              49
Sp. Atk              65
Sp. Def              65
Speed                45
Generation            1
Legendary         False
Name: 0, dtype: object

In [33]:
df.iloc[1:5]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [35]:
#Reading specific rows and columns

df.iloc[0:3, 1:4]

        Name Type 1  Type 2
0  Bulbasaur  Grass  Poison
1    Ivysaur  Grass  Poison
2   Venusaur  Grass  Poison

## Pandas unique() method

In [36]:
df['Name'].unique()

array(['Bulbasaur', 'Ivysaur', 'Venusaur', 'VenusaurMega Venusaur',
       'Charmander', 'Charmeleon', 'Charizard',
       'CharizardMega Charizard X', 'CharizardMega Charizard Y',
       'Squirtle', 'Wartortle', 'Blastoise', 'BlastoiseMega Blastoise',
       'Caterpie', 'Metapod', 'Butterfree', 'Weedle', 'Kakuna',
       'Beedrill', 'BeedrillMega Beedrill', 'Pidgey', 'Pidgeotto',
       'Pidgeot', 'PidgeotMega Pidgeot', 'Rattata', 'Raticate', 'Spearow',
       'Fearow', 'Ekans', 'Arbok', 'Pikachu', 'Raichu', 'Sandshrew',
       'Sandslash', 'Nidoran (Female)', 'Nidorina', 'Nidoqueen',
       'Nidoran (Male)', 'Nidorino', 'Nidoking', 'Clefairy', 'Clefable',
       'Vulpix', 'Ninetales', 'Jigglypuff', 'Wigglytuff', 'Zubat',
       'Golbat', 'Oddish', 'Gloom', 'Vileplume', 'Paras', 'Parasect',
       'Venonat', 'Venomoth', 'Diglett', 'Dugtrio', 'Meowth', 'Persian',
       'Psyduck', 'Golduck', 'Mankey', 'Primeape', 'Growlithe',
       'Arcanine', 'Poliwag', 'Poliwhirl', 'Poliwrath', 'Abra', 'Kadabra',
       'Alakazam', 'AlakazamMega Alakazam', 'Machop', 'Machoke',
       'Machamp', 'Bellsprout', 'Weepinbell', 'Victreebel', 'Tentacool',
       'Tentacruel', 'Geodude', 'Graveler', 'Golem', 'Ponyta', 'Rapidash',
       'Slowpoke', 'Slowbro', 'SlowbroMega Slowbro', 'Magnemite',
       'Magneton', "Farfetch'd", 'Doduo', 'Dodrio', 'Seel', 'Dewgong',
       'Grimer', 'Muk', 'Shellder', 'Cloyster', 'Gastly', 'Haunter',
       'Gengar', 'GengarMega Gengar', 'Onix', 'Drowzee', 'Hypno',
       'Krabby', 'Kingler', 'Voltorb', 'Electrode', 'Exeggcute',
       'Exeggutor', 'Cubone', 'Marowak', 'Hitmonlee', 'Hitmonchan',
       'Lickitung', 'Koffing', 'Weezing', 'Rhyhorn', 'Rhydon', 'Chansey',
       'Tangela', 'Kangaskhan', 'KangaskhanMega Kangaskhan', 'Horsea',
       'Seadra', 'Goldeen', 'Seaking', 'Staryu', 'Starmie', 'Mr. Mime',
       'Scyther', 'Jynx', 'Electabuzz', 'Magmar', 'Pinsir',
       'PinsirMega Pinsir', 'Tauros', 'Magikarp', 'Gyarados',
       'GyaradosMega Gyarados', 'Lapras', 'Ditto', 'Eevee', 'Vaporeon',
       'Jolteon', 'Flareon', 'Porygon', 'Omanyte', 'Omastar', 'Kabuto',
       'Kabutops', 'Aerodactyl', 'AerodactylMega Aerodactyl', 'Snorlax',
       'Articuno', 'Zapdos', 'Moltres', 'Dratini', 'Dragonair',
       'Dragonite', 'Mewtwo', 'MewtwoMega Mewtwo X',
       'MewtwoMega Mewtwo Y', 'Mew', 'Chikorita', 'Bayleef', 'Meganium',
       'Cyndaquil', 'Quilava', 'Typhlosion', 'Totodile', 'Croconaw',
       'Feraligatr', 'Sentret', 'Furret', 'Hoothoot', 'Noctowl', 'Ledyba',
       'Ledian', 'Spinarak', 'Ariados', 'Crobat', 'Chinchou', 'Lanturn',
       'Pichu', 'Cleffa', 'Igglybuff', 'Togepi', 'Togetic', 'Natu',
       'Xatu', 'Mareep', 'Flaaffy', 'Ampharos', 'AmpharosMega Ampharos',
       'Bellossom', 'Marill', 'Azumarill', 'Sudowoodo', 'Politoed',
       'Hoppip', 'Skiploom', 'Jumpluff', 'Aipom', 'Sunkern', 'Sunflora',
       'Yanma', 'Wooper', 'Quagsire', 'Espeon', 'Umbreon', 'Murkrow',
       'Slowking', 'Misdreavus', 'Unown', 'Wobbuffet', 'Girafarig',
       'Pineco', 'Forretress', 'Dunsparce', 'Gligar', 'Steelix',
       'SteelixMega Steelix', 'Snubbull', 'Granbull', 'Qwilfish',
       'Scizor', 'ScizorMega Scizor', 'Shuckle', 'Heracross',
       'HeracrossMega Heracross', 'Sneasel', 'Teddiursa', 'Ursaring',
       'Slugma', 'Magcargo', 'Swinub', 'Piloswine', 'Corsola', 'Remoraid',
       'Octillery', 'Delibird', 'Mantine', 'Skarmory', 'Houndour',
       'Houndoom', 'HoundoomMega Houndoom', 'Kingdra', 'Phanpy',
       'Donphan', 'Porygon2', 'Stantler', 'Smeargle', 'Tyrogue',
       'Hitmontop', 'Smoochum', 'Elekid', 'Magby', 'Miltank', 'Blissey',
       'Raikou', 'Entei', 'Suicune', 'Larvitar', 'Pupitar', 'Tyranitar',
       'TyranitarMega Tyranitar', 'Lugia', 'Ho-oh', 'Celebi', 'Treecko',
       'Grovyle', 'Sceptile', 'SceptileMega Sceptile', 'Torchic',
       'Combusken', 'Blaziken', 'BlazikenMega Blaziken', 'Mudkip',
       'Marshtomp', 'Swampert', 'SwampertMega Swampert', 'Poochyena',
       'Mightyena', 'Zigzagoon', 'Linoone', 'Wurmple', 'Silcoon',
       'Beautifly', 'Cascoon', 'Dustox', 'Lotad', 'Lombre', 'Ludicolo',
       'Seedot', 'Nuzleaf', 'Shiftry', 'Taillow', 'Swellow', 'Wingull',
       'Pelipper', 'Ralts', 'Kirlia', 'Gardevoir',
       'GardevoirMega Gardevoir', 'Surskit', 'Masquerain', 'Shroomish',
       'Breloom', 'Slakoth', 'Vigoroth', 'Slaking', 'Nincada', 'Ninjask',
       'Shedinja', 'Whismur', 'Loudred', 'Exploud', 'Makuhita',
       'Hariyama', 'Azurill', 'Nosepass', 'Skitty', 'Delcatty', 'Sableye',
       'SableyeMega Sableye', 'Mawile', 'MawileMega Mawile', 'Aron',
       'Lairon', 'Aggron', 'AggronMega Aggron', 'Meditite', 'Medicham',
       'MedichamMega Medicham', 'Electrike', 'Manectric',
       'ManectricMega Manectric', 'Plusle', 'Minun', 'Volbeat',
       'Illumise', 'Roselia', 'Gulpin', 'Swalot', 'Carvanha', 'Sharpedo',
       'SharpedoMega Sharpedo', 'Wailmer', 'Wailord', 'Numel', 'Camerupt',
       'CameruptMega Camerupt', 'Torkoal', 'Spoink', 'Grumpig', 'Spinda',
       'Trapinch', 'Vibrava', 'Flygon', 'Cacnea', 'Cacturne', 'Swablu',
       'Altaria', 'AltariaMega Altaria', 'Zangoose', 'Seviper',
       'Lunatone', 'Solrock', 'Barboach', 'Whiscash', 'Corphish',
       'Crawdaunt', 'Baltoy', 'Claydol', 'Lileep', 'Cradily', 'Anorith',
       'Armaldo', 'Feebas', 'Milotic', 'Castform', 'Kecleon', 'Shuppet',
       'Banette', 'BanetteMega Banette', 'Duskull', 'Dusclops', 'Tropius',
       'Chimecho', 'Absol', 'AbsolMega Absol', 'Wynaut', 'Snorunt',
       'Glalie', 'GlalieMega Glalie', 'Spheal', 'Sealeo', 'Walrein',
       'Clamperl', 'Huntail', 'Gorebyss', 'Relicanth', 'Luvdisc', 'Bagon',
       'Shelgon', 'Salamence', 'SalamenceMega Salamence', 'Beldum',
       'Metang', 'Metagross', 'MetagrossMega Metagross', 'Regirock',
       'Regice', 'Registeel', 'Latias', 'LatiasMega Latias', 'Latios',
       'LatiosMega Latios', 'Kyogre', 'KyogrePrimal Kyogre', 'Groudon',
       'GroudonPrimal Groudon', 'Rayquaza', 'RayquazaMega Rayquaza',
       'Jirachi', 'DeoxysNormal Forme', 'DeoxysAttack Forme',
       'DeoxysDefense Forme', 'DeoxysSpeed Forme', 'Turtwig', 'Grotle',
       'Torterra', 'Chimchar', 'Monferno', 'Infernape', 'Piplup',
       'Prinplup', 'Empoleon', 'Starly', 'Staravia', 'Staraptor',
       'Bidoof', 'Bibarel', 'Kricketot', 'Kricketune', 'Shinx', 'Luxio',
       'Luxray', 'Budew', 'Roserade', 'Cranidos', 'Rampardos', 'Shieldon',
       'Bastiodon', 'Burmy', 'WormadamPlant Cloak', 'WormadamSandy Cloak',
       'WormadamTrash Cloak', 'Mothim', 'Combee', 'Vespiquen',
       'Pachirisu', 'Buizel', 'Floatzel', 'Cherubi', 'Cherrim', 'Shellos',
       'Gastrodon', 'Ambipom', 'Drifloon', 'Drifblim', 'Buneary',
       'Lopunny', 'LopunnyMega Lopunny', 'Mismagius', 'Honchkrow',
       'Glameow', 'Purugly', 'Chingling', 'Stunky', 'Skuntank', 'Bronzor',
       'Bronzong', 'Bonsly', 'Mime Jr.', 'Happiny', 'Chatot', 'Spiritomb',
       'Gible', 'Gabite', 'Garchomp', 'GarchompMega Garchomp', 'Munchlax',
       'Riolu', 'Lucario', 'LucarioMega Lucario', 'Hippopotas',
       'Hippowdon', 'Skorupi', 'Drapion', 'Croagunk', 'Toxicroak',
       'Carnivine', 'Finneon', 'Lumineon', 'Mantyke', 'Snover',
       'Abomasnow', 'AbomasnowMega Abomasnow', 'Weavile', 'Magnezone',
       'Lickilicky', 'Rhyperior', 'Tangrowth', 'Electivire', 'Magmortar',
       'Togekiss', 'Yanmega', 'Leafeon', 'Glaceon', 'Gliscor',
       'Mamoswine', 'Porygon-Z', 'Gallade', 'GalladeMega Gallade',
       'Probopass', 'Dusknoir', 'Froslass', 'Rotom', 'RotomHeat Rotom',
       'RotomWash Rotom', 'RotomFrost Rotom', 'RotomFan Rotom',
       'RotomMow Rotom', 'Uxie', 'Mesprit', 'Azelf', 'Dialga', 'Palkia',
       'Heatran', 'Regigigas', 'GiratinaAltered Forme',
       'GiratinaOrigin Forme', 'Cresselia', 'Phione', 'Manaphy',
       'Darkrai', 'ShayminLand Forme', 'ShayminSky Forme', 'Arceus',
       'Victini', 'Snivy', 'Servine', 'Serperior', 'Tepig', 'Pignite',
       'Emboar', 'Oshawott', 'Dewott', 'Samurott', 'Patrat', 'Watchog',
       'Lillipup', 'Herdier', 'Stoutland', 'Purrloin', 'Liepard',
       'Pansage', 'Simisage', 'Pansear', 'Simisear', 'Panpour',
       'Simipour', 'Munna', 'Musharna', 'Pidove', 'Tranquill', 'Unfezant',
       'Blitzle', 'Zebstrika', 'Roggenrola', 'Boldore', 'Gigalith',
       'Woobat', 'Swoobat', 'Drilbur', 'Excadrill', 'Audino',
       'AudinoMega Audino', 'Timburr', 'Gurdurr', 'Conkeldurr', 'Tympole',
       'Palpitoad', 'Seismitoad', 'Throh', 'Sawk', 'Sewaddle', 'Swadloon',
       'Leavanny', 'Venipede', 'Whirlipede', 'Scolipede', 'Cottonee',
       'Whimsicott', 'Petilil', 'Lilligant', 'Basculin', 'Sandile',
       'Krokorok', 'Krookodile', 'Darumaka', 'DarmanitanStandard Mode',
       'DarmanitanZen Mode', 'Maractus', 'Dwebble', 'Crustle', 'Scraggy',
       'Scrafty', 'Sigilyph', 'Yamask', 'Cofagrigus', 'Tirtouga',
       'Carracosta', 'Archen', 'Archeops', 'Trubbish', 'Garbodor',
       'Zorua', 'Zoroark', 'Minccino', 'Cinccino', 'Gothita', 'Gothorita',
       'Gothitelle', 'Solosis', 'Duosion', 'Reuniclus', 'Ducklett',
       'Swanna', 'Vanillite', 'Vanillish', 'Vanilluxe', 'Deerling',
       'Sawsbuck', 'Emolga', 'Karrablast', 'Escavalier', 'Foongus',
       'Amoonguss', 'Frillish', 'Jellicent', 'Alomomola', 'Joltik',
       'Galvantula', 'Ferroseed', 'Ferrothorn', 'Klink', 'Klang',
       'Klinklang', 'Tynamo', 'Eelektrik', 'Eelektross', 'Elgyem',
       'Beheeyem', 'Litwick', 'Lampent', 'Chandelure', 'Axew', 'Fraxure',
       'Haxorus', 'Cubchoo', 'Beartic', 'Cryogonal', 'Shelmet',
       'Accelgor', 'Stunfisk', 'Mienfoo', 'Mienshao', 'Druddigon',
       'Golett', 'Golurk', 'Pawniard', 'Bisharp', 'Bouffalant', 'Rufflet',
       'Braviary', 'Vullaby', 'Mandibuzz', 'Heatmor', 'Durant', 'Deino',
       'Zweilous', 'Hydreigon', 'Larvesta', 'Volcarona', 'Cobalion',
       'Terrakion', 'Virizion', 'TornadusIncarnate Forme',
       'TornadusTherian Forme', 'ThundurusIncarnate Forme',
       'ThundurusTherian Forme', 'Reshiram', 'Zekrom',
       'LandorusIncarnate Forme', 'LandorusTherian Forme', 'Kyurem',
       'KyuremBlack Kyurem', 'KyuremWhite Kyurem', 'KeldeoOrdinary Forme',
       'KeldeoResolute Forme', 'MeloettaAria Forme',
       'MeloettaPirouette Forme', 'Genesect', 'Chespin', 'Quilladin',
       'Chesnaught', 'Fennekin', 'Braixen', 'Delphox', 'Froakie',
       'Frogadier', 'Greninja', 'Bunnelby', 'Diggersby', 'Fletchling',
       'Fletchinder', 'Talonflame', 'Scatterbug', 'Spewpa', 'Vivillon',
       'Litleo', 'Pyroar', 'FlabÃ©bÃ©', 'Floette', 'Florges', 'Skiddo',
       'Gogoat', 'Pancham', 'Pangoro', 'Furfrou', 'Espurr',
       'MeowsticMale', 'MeowsticFemale', 'Honedge', 'Doublade',
       'AegislashBlade Forme', 'AegislashShield Forme', 'Spritzee',
       'Aromatisse', 'Swirlix', 'Slurpuff', 'Inkay', 'Malamar', 'Binacle',
       'Barbaracle', 'Skrelp', 'Dragalge', 'Clauncher', 'Clawitzer',
       'Helioptile', 'Heliolisk', 'Tyrunt', 'Tyrantrum', 'Amaura',
       'Aurorus', 'Sylveon', 'Hawlucha', 'Dedenne', 'Carbink', 'Goomy',
       'Sliggoo', 'Goodra', 'Klefki', 'Phantump', 'Trevenant',
       'PumpkabooAverage Size', 'PumpkabooSmall Size',
       'PumpkabooLarge Size', 'PumpkabooSuper Size',
       'GourgeistAverage Size', 'GourgeistSmall Size',
       'GourgeistLarge Size', 'GourgeistSuper Size', 'Bergmite',
       'Avalugg', 'Noibat', 'Noivern', 'Xerneas', 'Yveltal',
       'Zygarde50% Forme', 'Diancie', 'DiancieMega Diancie',
       'HoopaHoopa Confined', 'HoopaHoopa Unbound', 'Volcanion'],
      dtype=object)

In [37]:
#to figure out all the names with Poison Type 2

df1 = df[df['Type 2'] == 'Poison']
df1

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
16,13,Weedle,Bug,Poison,40,35,30,20,20,50,1,False
17,14,Kakuna,Bug,Poison,45,25,50,25,25,35,1,False
18,15,Beedrill,Bug,Poison,65,90,40,45,80,75,1,False
19,15,BeedrillMega Beedrill,Bug,Poison,65,150,40,15,80,145,1,False
48,43,Oddish,Grass,Poison,45,50,55,75,65,30,1,False
49,44,Gloom,Grass,Poison,60,65,70,85,75,40,1,False
50,45,Vileplume,Grass,Poison,75,80,85,110,90,50,1,False
53,48,Venonat,Bug,Poison,60,55,50,40,55,45,1,False
54,49,Venomoth,Bug,Poison,70,65,60,90,75,90,1,False
75,69,Bellsprout,Grass,Poison,50,75,35,70,30,40,1,False
76,70,Weepinbell,Grass,Poison,65,90,50,85,45,55,1,False
77,71,Victreebel,Grass,Poison,80,105,65,100,70,70,1,False
78,72,Tentacool,Water,Poison,40,40,35,50,100,70,1,False
79,73,Tentacruel,Water,Poison,80,70,65,80,120,100,1,False
99,92,Gastly,Ghost,Poison,30,35,30,100,35,80,1,False
100,93,Haunter,Ghost,Poison,45,50,45,115,55,95,1,False
101,94,Gengar,Ghost,Poison,60,65,60,130,75,110,1,False
102,94,GengarMega Gengar,Ghost,Poison,60,65,80,170,95,130,1,False
181,167,Spinarak,Bug,Poison,40,60,40,40,40,30,2,False
182,168,Ariados,Bug,Poison,70,90,70,60,60,40,2,False
227,211,Qwilfish,Water,Poison,65,95,75,55,55,85,2,False
292,269,Dustox,Bug,Poison,60,50,70,50,90,65,3,False
344,315,Roselia,Grass,Poison,50,60,45,100,80,65,3,False
451,406,Budew,Grass,Poison,40,30,35,50,70,55,4,False
452,407,Roserade,Grass,Poison,60,70,65,125,105,90,4,False
603,543,Venipede,Bug,Poison,30,45,59,30,39,57,5,False
604,544,Whirlipede,Bug,Poison,40,55,99,40,79,47,5,False
605,545,Scolipede,Bug,Poison,60,100,89,55,69,112,5,False
651,590,Foongus,Grass,Poison,69,55,45,55,55,15,5,False
652,591,Amoonguss,Grass,Poison,114,85,70,85,80,30,5,False

In [46]:
#Or you can use loc

#Reading through with loc

df.loc[df['Type 2'] == 'Poison']

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
16,13,Weedle,Bug,Poison,40,35,30,20,20,50,1,False
17,14,Kakuna,Bug,Poison,45,25,50,25,25,35,1,False
18,15,Beedrill,Bug,Poison,65,90,40,45,80,75,1,False
19,15,BeedrillMega Beedrill,Bug,Poison,65,150,40,15,80,145,1,False
48,43,Oddish,Grass,Poison,45,50,55,75,65,30,1,False
49,44,Gloom,Grass,Poison,60,65,70,85,75,40,1,False
50,45,Vileplume,Grass,Poison,75,80,85,110,90,50,1,False
53,48,Venonat,Bug,Poison,60,55,50,40,55,45,1,False
54,49,Venomoth,Bug,Poison,70,65,60,90,75,90,1,False
75,69,Bellsprout,Grass,Poison,50,75,35,70,30,40,1,False
76,70,Weepinbell,Grass,Poison,65,90,50,85,45,55,1,False
77,71,Victreebel,Grass,Poison,80,105,65,100,70,70,1,False
78,72,Tentacool,Water,Poison,40,40,35,50,100,70,1,False
79,73,Tentacruel,Water,Poison,80,70,65,80,120,100,1,False
99,92,Gastly,Ghost,Poison,30,35,30,100,35,80,1,False
100,93,Haunter,Ghost,Poison,45,50,45,115,55,95,1,False
101,94,Gengar,Ghost,Poison,60,65,60,130,75,110,1,False
102,94,GengarMega Gengar,Ghost,Poison,60,65,80,170,95,130,1,False
181,167,Spinarak,Bug,Poison,40,60,40,40,40,30,2,False
182,168,Ariados,Bug,Poison,70,90,70,60,60,40,2,False
227,211,Qwilfish,Water,Poison,65,95,75,55,55,85,2,False
292,269,Dustox,Bug,Poison,60,50,70,50,90,65,3,False
344,315,Roselia,Grass,Poison,50,60,45,100,80,65,3,False
451,406,Budew,Grass,Poison,40,30,35,50,70,55,4,False
452,407,Roserade,Grass,Poison,60,70,65,125,105,90,4,False
603,543,Venipede,Bug,Poison,30,45,59,30,39,57,5,False
604,544,Whirlipede,Bug,Poison,40,55,99,40,79,47,5,False
605,545,Scolipede,Bug,Poison,60,100,89,55,69,112,5,False
651,590,Foongus,Grass,Poison,69,55,45,55,55,15,5,False
652,591,Amoonguss,Grass,Poison,114,85,70,85,80,30,5,False

In [44]:
#to iterate through rows you can use a for loop

for index, row in df.iterrows():
    print(index, row)
    print('\n')

In [40]:
#if we want just the Name and the index for each row
for index, row in df.iterrows():
    print(index, row['Name'])

0 Bulbasaur
1 Ivysaur
2 Venusaur
3 VenusaurMega Venusaur
4 Charmander
5 Charmeleon
6 Charizard
7 CharizardMega Charizard X
8 CharizardMega Charizard Y
9 Squirtle
10 Wartortle
11 Blastoise
12 BlastoiseMega Blastoise
13 Caterpie
14 Metapod
15 Butterfree
16 Weedle
17 Kakuna
18 Beedrill
19 BeedrillMega Beedrill
20 Pidgey
21 Pidgeotto
22 Pidgeot
23 PidgeotMega Pidgeot
24 Rattata
25 Raticate
26 Spearow
27 Fearow
28 Ekans
29 Arbok
30 Pikachu
31 Raichu
32 Sandshrew
33 Sandslash
34 Nidoran (Female)
35 Nidorina
36 Nidoqueen
37 Nidoran (Male)
38 Nidorino
39 Nidoking
40 Clefairy
41 Clefable
42 Vulpix
43 Ninetales
44 Jigglypuff
45 Wigglytuff
46 Zubat
47 Golbat
48 Oddish
49 Gloom
50 Vileplume
51 Paras
52 Parasect
53 Venonat
54 Venomoth
55 Diglett
56 Dugtrio
57 Meowth
58 Persian
59 Psyduck
60 Golduck
61 Mankey
62 Primeape
63 Growlithe
64 Arcanine
65 Poliwag
66 Poliwhirl
67 Poliwrath
68 Abra
69 Kadabra
70 Alakazam
71 AlakazamMega Alakazam
72 Machop
73 Machoke
74 Machamp
75 Bellsprout
76 Weepinbell
77 Victreebel
78 Tentacool
79 Tentacruel
80 Geodude
81 Graveler
82 Golem
83 Ponyta
84 Rapidash
85 Slowpoke
86 Slowbro
87 SlowbroMega Slowbro
88 Magnemite
89 Magneton
90 Farfetch'd
91 Doduo
92 Dodrio
93 Seel
94 Dewgong
95 Grimer
96 Muk
97 Shellder
98 Cloyster
99 Gastly
100 Haunter
101 Gengar
102 GengarMega Gengar
103 Onix
104 Drowzee
105 Hypno
106 Krabby
107 Kingler
108 Voltorb
109 Electrode
110 Exeggcute
111 Exeggutor
112 Cubone
113 Marowak
114 Hitmonlee
115 Hitmonchan
116 Lickitung
117 Koffing
118 Weezing
119 Rhyhorn
120 Rhydon
121 Chansey
122 Tangela
123 Kangaskhan
124 KangaskhanMega Kangaskhan
125 Horsea
126 Seadra
127 Goldeen
128 Seaking
129 Staryu
130 Starmie
131 Mr. Mime
132 Scyther
133 Jynx
134 Electabuzz
135 Magmar
136 Pinsir
137 PinsirMega Pinsir
138 Tauros
139 Magikarp
140 Gyarados
141 GyaradosMega Gyarados
142 Lapras
143 Ditto
144 Eevee
145 Vaporeon
146 Jolteon
147 Flareon
148 Porygon
149 Omanyte
150 Omastar
151 Kabuto
152 Kabutops
153 Aerodactyl
154 AerodactylMega Aerodactyl
155 Snorlax
156 Articuno
157 Zapdos
158 Moltres
159 Dratini
160 Dragonair
161 Dragonite
162 Mewtwo
163 MewtwoMega Mewtwo X
164 MewtwoMega Mewtwo Y
165 Mew
166 Chikorita
167 Bayleef
168 Meganium
169 Cyndaquil
170 Quilava
171 Typhlosion
172 Totodile
173 Croconaw
174 Feraligatr
175 Sentret
176 Furret
177 Hoothoot
178 Noctowl
179 Ledyba
180 Ledian
181 Spinarak
182 Ariados
183 Crobat
184 Chinchou
185 Lanturn
186 Pichu
187 Cleffa
188 Igglybuff
189 Togepi
190 Togetic
191 Natu
192 Xatu
193 Mareep
194 Flaaffy
195 Ampharos
196 AmpharosMega Ampharos
197 Bellossom
198 Marill
199 Azumarill
200 Sudowoodo
201 Politoed
202 Hoppip
203 Skiploom
204 Jumpluff
205 Aipom
206 Sunkern
207 Sunflora
208 Yanma
209 Wooper
210 Quagsire
211 Espeon
212 Umbreon
213 Murkrow
214 Slowking
215 Misdreavus
216 Unown
217 Wobbuffet
218 Girafarig
219 Pineco
220 Forretress
221 Dunsparce
222 Gligar
223 Steelix
224 SteelixMega Steelix
225 Snubbull
226 Granbull
227 Qwilfish
228 Scizor
229 ScizorMega Scizor
230 Shuckle
231 Heracross
232 HeracrossMega Heracross
233 Sneasel
234 Teddiursa
235 Ursaring
236 Slugma
237 Magcargo
238 Swinub
239 Piloswine
240 Corsola
241 Remoraid
242 Octillery
243 Delibird
244 Mantine
245 Skarmory
246 Houndour
247 Houndoom
248 HoundoomMega Houndoom
249 Kingdra
250 Phanpy
251 Donphan
252 Porygon2
253 Stantler
254 Smeargle
255 Tyrogue
256 Hitmontop
257 Smoochum
258 Elekid
259 Magby
260 Miltank
261 Blissey
262 Raikou
263 Entei
264 Suicune
265 Larvitar
266 Pupitar
267 Tyranitar
268 TyranitarMega Tyranitar
269 Lugia
270 Ho-oh
271 Celebi
272 Treecko
273 Grovyle
274 Sceptile
275 SceptileMega Sceptile
276 Torchic
277 Combusken
278 Blaziken
279 BlazikenMega Blaziken
280 Mudkip
281 Marshtomp
282 Swampert
283 SwampertMega Swampert
284 Poochyena
285 Mightyena
286 Zigzagoon
287 Linoone
288 Wurmple
289 Silcoon
290 Beautifly
291 Cascoon
292 Dustox
293 Lotad
294 Lombre
295 Ludicolo
296 Seedot
297 Nuzleaf
298 Shiftry
299 Taillow
300 Swellow
301 Wingull
302 Pelipper
303 Ralts
304 Kirlia
305 Gardevoir
306 GardevoirMega Gardevoir
307 Surskit
308 Masquerain
309 Shroomish
310 Breloom
311 Slakoth
312 Vigoroth
313 Slaking
314 Nincada
315 Ninjask
316 Shedinja
317 Whismur
318 Loudred
319 Exploud
320 Makuhita
321 Hariyama
322 Azurill
323 Nosepass
324 Skitty
325 Delcatty
326 Sableye
327 SableyeMega Sableye
328 Mawile
329 MawileMega Mawile
330 Aron
331 Lairon
332 Aggron
333 AggronMega Aggron
334 Meditite
335 Medicham
336 MedichamMega Medicham
337 Electrike
338 Manectric
339 ManectricMega Manectric
340 Plusle
341 Minun
342 Volbeat
343 Illumise
344 Roselia
345 Gulpin
346 Swalot
347 Carvanha
348 Sharpedo
349 SharpedoMega Sharpedo
350 Wailmer
351 Wailord
352 Numel
353 Camerupt
354 CameruptMega Camerupt
355 Torkoal
356 Spoink
357 Grumpig
358 Spinda
359 Trapinch
360 Vibrava
361 Flygon
362 Cacnea
363 Cacturne
364 Swablu
365 Altaria
366 AltariaMega Altaria
367 Zangoose
368 Seviper
369 Lunatone
370 Solrock
371 Barboach
372 Whiscash
373 Corphish
374 Crawdaunt
375 Baltoy
376 Claydol
377 Lileep
378 Cradily
379 Anorith
380 Armaldo
381 Feebas
382 Milotic
383 Castform
384 Kecleon
385 Shuppet
386 Banette
387 BanetteMega Banette
388 Duskull
389 Dusclops
390 Tropius
391 Chimecho
392 Absol
393 AbsolMega Absol
394 Wynaut
395 Snorunt
396 Glalie
397 GlalieMega Glalie
398 Spheal
399 Sealeo
400 Walrein
401 Clamperl
402 Huntail
403 Gorebyss
404 Relicanth
405 Luvdisc
406 Bagon
407 Shelgon
408 Salamence
409 SalamenceMega Salamence
410 Beldum
411 Metang
412 Metagross
413 MetagrossMega Metagross
414 Regirock
415 Regice
416 Registeel
417 Latias
418 LatiasMega Latias
419 Latios
420 LatiosMega Latios
421 Kyogre
422 KyogrePrimal Kyogre
423 Groudon
424 GroudonPrimal Groudon
425 Rayquaza
426 RayquazaMega Rayquaza
427 Jirachi
428 DeoxysNormal Forme
429 DeoxysAttack Forme
430 DeoxysDefense Forme
431 DeoxysSpeed Forme
432 Turtwig
433 Grotle
434 Torterra
435 Chimchar
436 Monferno
437 Infernape
438 Piplup
439 Prinplup
440 Empoleon
441 Starly
442 Staravia
443 Staraptor
444 Bidoof
445 Bibarel
446 Kricketot
447 Kricketune
448 Shinx
449 Luxio
450 Luxray
451 Budew
452 Roserade
453 Cranidos
454 Rampardos
455 Shieldon
456 Bastiodon
457 Burmy
458 WormadamPlant Cloak
459 WormadamSandy Cloak
460 WormadamTrash Cloak
461 Mothim
462 Combee
463 Vespiquen
464 Pachirisu
465 Buizel
466 Floatzel
467 Cherubi
468 Cherrim
469 Shellos
470 Gastrodon
471 Ambipom
472 Drifloon
473 Drifblim
474 Buneary
475 Lopunny
476 LopunnyMega Lopunny
477 Mismagius
478 Honchkrow
479 Glameow
480 Purugly
481 Chingling
482 Stunky
483 Skuntank
484 Bronzor
485 Bronzong
486 Bonsly
487 Mime Jr.
488 Happiny
489 Chatot
490 Spiritomb
491 Gible
492 Gabite
493 Garchomp
494 GarchompMega Garchomp
495 Munchlax
496 Riolu
497 Lucario
498 LucarioMega Lucario
499 Hippopotas
500 Hippowdon
501 Skorupi
502 Drapion
503 Croagunk
504 Toxicroak
505 Carnivine
506 Finneon
507 Lumineon
508 Mantyke
509 Snover
510 Abomasnow
511 AbomasnowMega Abomasnow
512 Weavile
513 Magnezone
514 Lickilicky
515 Rhyperior
516 Tangrowth
517 Electivire
518 Magmortar
519 Togekiss
520 Yanmega
521 Leafeon
522 Glaceon
523 Gliscor
524 Mamoswine
525 Porygon-Z
526 Gallade
527 GalladeMega Gallade
528 Probopass
529 Dusknoir
530 Froslass
531 Rotom
532 RotomHeat Rotom
533 RotomWash Rotom
534 RotomFrost Rotom
535 RotomFan Rotom
536 RotomMow Rotom
537 Uxie
538 Mesprit
539 Azelf
540 Dialga
541 Palkia
542 Heatran
543 Regigigas
544 GiratinaAltered Forme
545 GiratinaOrigin Forme
546 Cresselia
547 Phione
548 Manaphy
549 Darkrai
550 ShayminLand Forme
551 ShayminSky Forme
552 Arceus
553 Victini
554 Snivy
555 Servine
556 Serperior
557 Tepig
558 Pignite
559 Emboar
560 Oshawott
561 Dewott
562 Samurott
563 Patrat
564 Watchog
565 Lillipup
566 Herdier
567 Stoutland
568 Purrloin
569 Liepard
570 Pansage
571 Simisage
572 Pansear
573 Simisear
574 Panpour
575 Simipour
576 Munna
577 Musharna
578 Pidove
579 Tranquill
580 Unfezant
581 Blitzle
582 Zebstrika
583 Roggenrola
584 Boldore
585 Gigalith
586 Woobat
587 Swoobat
588 Drilbur
589 Excadrill
590 Audino
591 AudinoMega Audino
592 Timburr
593 Gurdurr
594 Conkeldurr
595 Tympole
596 Palpitoad
597 Seismitoad
598 Throh
599 Sawk
600 Sewaddle
601 Swadloon
602 Leavanny
603 Venipede
604 Whirlipede
605 Scolipede
606 Cottonee
607 Whimsicott
608 Petilil
609 Lilligant
610 Basculin
611 Sandile
612 Krokorok
613 Krookodile
614 Darumaka
615 DarmanitanStandard Mode
616 DarmanitanZen Mode
617 Maractus
618 Dwebble
619 Crustle
620 Scraggy
621 Scrafty
622 Sigilyph
623 Yamask
624 Cofagrigus
625 Tirtouga
626 Carracosta
627 Archen
628 Archeops
629 Trubbish
630 Garbodor
631 Zorua
632 Zoroark
633 Minccino
634 Cinccino
635 Gothita
636 Gothorita
637 Gothitelle
638 Solosis
639 Duosion
640 Reuniclus
641 Ducklett
642 Swanna
643 Vanillite
644 Vanillish
645 Vanilluxe
646 Deerling
647 Sawsbuck
648 Emolga
649 Karrablast
650 Escavalier
651 Foongus
652 Amoonguss
653 Frillish
654 Jellicent
655 Alomomola
656 Joltik
657 Galvantula
658 Ferroseed
659 Ferrothorn
660 Klink
661 Klang
662 Klinklang
663 Tynamo
664 Eelektrik
665 Eelektross
666 Elgyem
667 Beheeyem

668 Litwick
669 Lampent
670 Chandelure
671 Axew
672 Fraxure
673 Haxorus
674 Cubchoo
675 Beartic
676 Cryogonal
677 Shelmet
678 Accelgor
679 Stunfisk
680 Mienfoo
681 Mienshao
682 Druddigon
683 Golett
684 Golurk
685 Pawniard
686 Bisharp
687 Bouffalant
688 Rufflet
689 Braviary
690 Vullaby
691 Mandibuzz
692 Heatmor
693 Durant
694 Deino
695 Zweilous
696 Hydreigon
697 Larvesta
698 Volcarona
699 Cobalion
700 Terrakion
701 Virizion
702 TornadusIncarnate Forme
703 TornadusTherian Forme
704 ThundurusIncarnate Forme
705 ThundurusTherian Forme
706 Reshiram
707 Zekrom
708 LandorusIncarnate Forme
709 LandorusTherian Forme
710 Kyurem
711 KyuremBlack Kyurem
712 KyuremWhite Kyurem
713 KeldeoOrdinary Forme
714 KeldeoResolute Forme
715 MeloettaAria Forme
716 MeloettaPirouette Forme
717 Genesect
718 Chespin
719 Quilladin
720 Chesnaught
721 Fennekin
722 Braixen
723 Delphox
724 Froakie
725 Frogadier
726 Greninja
727 Bunnelby
728 Diggersby
729 Fletchling
730 Fletchinder
731 Talonflame
732 Scatterbug
733 Spewpa
734 Vivillon
735 Litleo
736 Pyroar
737 FlabÃ©bÃ©
738 Floette
739 Florges
740 Skiddo
741 Gogoat
742 Pancham
743 Pangoro
744 Furfrou
745 Espurr
746 MeowsticMale
747 MeowsticFemale
748 Honedge
749 Doublade
750 AegislashBlade Forme
751 AegislashShield Forme
752 Spritzee
753 Aromatisse
754 Swirlix
755 Slurpuff
756 Inkay
757 Malamar
758 Binacle
759 Barbaracle
760 Skrelp
761 Dragalge
762 Clauncher
763 Clawitzer
764 Helioptile
765 Heliolisk
766 Tyrunt
767 Tyrantrum
768 Amaura
769 Aurorus
770 Sylveon
771 Hawlucha
772 Dedenne
773 Carbink
774 Goomy
775 Sliggoo
776 Goodra
777 Klefki
778 Phantump
779 Trevenant
780 PumpkabooAverage Size
781 PumpkabooSmall Size
782 PumpkabooLarge Size
783 PumpkabooSuper Size
784 GourgeistAverage Size
785 GourgeistSmall Size
786 GourgeistLarge Size
787 GourgeistSuper Size
788 Bergmite
789 Avalugg
790 Noibat
791 Noivern
792 Xerneas
793 Yveltal
794 Zygarde50% Forme
795 Diancie
796 DiancieMega Diancie
797 HoopaHoopa Confined
798 HoopaHoopa Unbound
799 Volcanion

## Sorting and Describing data

In [48]:
#we can use describe() method to show us useful stuffs like mean, standard deviation, min, max, etc

df.describe()

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [49]:
#sorting values

df.sort_values('Name') #this prints 'Name' data in an alphabetical order

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True

In [50]:
#in descending order

df.sort_values('Name', ascending=False)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False

In [51]:
#we can combined two columns

df.sort_values(['Type 1', 'HP']) #for descending data you can pass the ascending args

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
316,292,Shedinja,Bug,Ghost,1,90,45,30,30,40,3,False
230,213,Shuckle,Bug,Rock,20,10,230,10,230,5,2,False
462,415,Combee,Bug,Flying,30,30,42,30,42,70,4,False
603,543,Venipede,Bug,Poison,30,45,59,30,39,57,5,False
314,290,Nincada,Bug,Ground,31,45,90,30,30,40,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...
142,131,Lapras,Water,Ice,130,85,80,85,95,60,1,False
145,134,Vaporeon,Water,NaN,130,65,60,110,95,65,1,False
350,320,Wailmer,Water,NaN,130,70,35,70,35,60,3,False
655,594,Alomomola,Water,NaN,165,75,80,40,45,65,5,False
351,321,Wailord,Water,NaN,170,90,45,90,45,60,3,False

In [52]:
#you can manipulate the ascending args further

df.sort_values(['Type 1', 'HP'], ascending=[1,0]) #1= True, 2=False: Type 1 ascends, HP descends

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
520,469,Yanmega,Bug,Flying,86,76,86,116,56,95,4,False
698,637,Volcarona,Bug,Fire,85,60,65,135,105,100,5,False
231,214,Heracross,Bug,Fighting,80,125,75,40,95,85,2,False
232,214,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,2,False
678,617,Accelgor,Bug,NaN,80,70,40,100,60,145,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...
106,98,Krabby,Water,NaN,30,105,90,25,25,50,1,False
125,116,Horsea,Water,NaN,30,40,70,70,25,60,1,False
129,120,Staryu,Water,NaN,30,45,55,70,55,85,1,False
139,129,Magikarp,Water,NaN,20,10,55,15,20,80,1,False
381,349,Feebas,Water,NaN,20,15,20,10,55,80,3,False

## Making more changes to data

In [63]:
#Creating a new column: Let's create 'Total column' which is the addition of HP, Attack, Defense, Sp. Atk, Sp. Def, Speed

df['Total'] = df['HP'] + df['Attack'] + df['Defense'] + df['Sp. Atk'] + df['Sp. Def'] + df['Speed']

df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,600
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,700
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600

In [64]:
#Or use a shorter method

df['Total2'] = df.iloc[:, 4:10].sum(axis=1) # : for all rows, 4:10 for columns of index 4 to index 9, axis=0 for adding vertically, axis=1 for horizontal operations
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total,Total2
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,600,600
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,700,700
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,600,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600,600

In [65]:
#Dropping a column: lets remove column 'Total2'

df = df.drop(columns=['Total2'])
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,600
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,700
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600

In [66]:
#Rearranging columns

#create a list of columns
col = list(df.columns)

#arrange using indexes
df = df[col[0:4] + [col[-1]] + col[4:12]]
df.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

## Saving our Data (Exporting to any file)

In [67]:
# saving to csv format: you'll find the 'updated pokemon file in the same directory'

df.to_csv('updated pokemon.csv')

In [68]:
#if you open the file you can choose not to save the index column with it. To do that we can pass;

df.to_csv('updated pokemon.csv', index=False)

In [69]:
#saving to excel format

df.to_excel('updated pokemon.xlsx', index=False)

In [71]:
#saving to txt format

df.to_csv('updated pokemon.txt', index=False, sep='\t')

## Filtering Our Data

In [72]:
#To set Type 1 to grass and Type 2 to poison: note in pandas 'and' = &; 'or' = |

df.loc[(df['Type 1'] == 'Grass') & (df['Type 2'] == 'Poison')]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
48,43,Oddish,Grass,Poison,320,45,50,55,75,65,30,1,False
49,44,Gloom,Grass,Poison,395,60,65,70,85,75,40,1,False
50,45,Vileplume,Grass,Poison,490,75,80,85,110,90,50,1,False
75,69,Bellsprout,Grass,Poison,300,50,75,35,70,30,40,1,False
76,70,Weepinbell,Grass,Poison,390,65,90,50,85,45,55,1,False
77,71,Victreebel,Grass,Poison,490,80,105,65,100,70,70,1,False
344,315,Roselia,Grass,Poison,400,50,60,45,100,80,65,3,False
451,406,Budew,Grass,Poison,280,40,30,35,50,70,55,4,False
452,407,Roserade,Grass,Poison,515,60,70,65,125,105,90,4,False
651,590,Foongus,Grass,Poison,294,69,55,45,55,55,15,5,False
652,591,Amoonguss,Grass,Poison,464,114,85,70,85,80,30,5,False

In [73]:
#or 
df[(df['Type 1'] == 'Grass') & (df['Type 2'] == 'Poison')]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
48,43,Oddish,Grass,Poison,320,45,50,55,75,65,30,1,False
49,44,Gloom,Grass,Poison,395,60,65,70,85,75,40,1,False
50,45,Vileplume,Grass,Poison,490,75,80,85,110,90,50,1,False
75,69,Bellsprout,Grass,Poison,300,50,75,35,70,30,40,1,False
76,70,Weepinbell,Grass,Poison,390,65,90,50,85,45,55,1,False
77,71,Victreebel,Grass,Poison,490,80,105,65,100,70,70,1,False
344,315,Roselia,Grass,Poison,400,50,60,45,100,80,65,3,False
451,406,Budew,Grass,Poison,280,40,30,35,50,70,55,4,False
452,407,Roserade,Grass,Poison,515,60,70,65,125,105,90,4,False
651,590,Foongus,Grass,Poison,294,69,55,45,55,55,15,5,False
652,591,Amoonguss,Grass,Poison,464,114,85,70,85,80,30,5,False

In [75]:
df.loc[(df['Type 1'] == 'Grass') & (df['Type 2'] == 'Poison') & (df['Speed'] > 40)]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
50,45,Vileplume,Grass,Poison,490,75,80,85,110,90,50,1,False
76,70,Weepinbell,Grass,Poison,390,65,90,50,85,45,55,1,False
77,71,Victreebel,Grass,Poison,490,80,105,65,100,70,70,1,False
344,315,Roselia,Grass,Poison,400,50,60,45,100,80,65,3,False
451,406,Budew,Grass,Poison,280,40,30,35,50,70,55,4,False
452,407,Roserade,Grass,Poison,515,60,70,65,125,105,90,4,False

In [76]:
#using or

df.loc[(df['Type 1'] == 'Grass') | (df['Type 2'] == 'Poison')]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
16,13,Weedle,Bug,Poison,195,40,35,30,20,20,50,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
718,650,Chespin,Grass,NaN,313,56,61,65,48,45,38,6,False
719,651,Quilladin,Grass,NaN,405,61,78,95,56,58,57,6,False
720,652,Chesnaught,Grass,Fighting,530,88,107,122,74,75,64,6,False
740,672,Skiddo,Grass,NaN,350,66,65,48,62,57,52,6,False
741,673,Gogoat,Grass,NaN,531,123,100,62,97,81,68,6,False

In [78]:
#sometimes we might need to work with the new df we've created hence we can rest index

new_df = df.loc[(df['Type 1'] == 'Grass') & (df['Type 2'] == 'Poison') & (df['Speed'] > 40)]
new_df = new_df.reset_index()
new_df

,index,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,50,45,Vileplume,Grass,Poison,490,75,80,85,110,90,50,1,False
5,76,70,Weepinbell,Grass,Poison,390,65,90,50,85,45,55,1,False
6,77,71,Victreebel,Grass,Poison,490,80,105,65,100,70,70,1,False
7,344,315,Roselia,Grass,Poison,400,50,60,45,100,80,65,3,False
8,451,406,Budew,Grass,Poison,280,40,30,35,50,70,55,4,False
9,452,407,Roserade,Grass,Poison,515,60,70,65,125,105,90,4,False

In [79]:
#from above the df automatically creates a new column for the previous index, we can drop that by using:

new_df = df.loc[(df['Type 1'] == 'Grass') & (df['Type 2'] == 'Poison') & (df['Speed'] > 40)]
new_df = new_df.reset_index(drop=True)
new_df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,45,Vileplume,Grass,Poison,490,75,80,85,110,90,50,1,False
5,70,Weepinbell,Grass,Poison,390,65,90,50,85,45,55,1,False
6,71,Victreebel,Grass,Poison,490,80,105,65,100,70,70,1,False
7,315,Roselia,Grass,Poison,400,50,60,45,100,80,65,3,False
8,406,Budew,Grass,Poison,280,40,30,35,50,70,55,4,False
9,407,Roserade,Grass,Poison,515,60,70,65,125,105,90,4,False

In [80]:
#we could just set it inplace rather than equate it to a new df again

new_df = df.loc[(df['Type 1'] == 'Grass') & (df['Type 2'] == 'Poison') & (df['Speed'] > 40)]
new_df.reset_index(drop=True, inplace=True)
new_df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,45,Vileplume,Grass,Poison,490,75,80,85,110,90,50,1,False
5,70,Weepinbell,Grass,Poison,390,65,90,50,85,45,55,1,False
6,71,Victreebel,Grass,Poison,490,80,105,65,100,70,70,1,False
7,315,Roselia,Grass,Poison,400,50,60,45,100,80,65,3,False
8,406,Budew,Grass,Poison,280,40,30,35,50,70,55,4,False
9,407,Roserade,Grass,Poison,515,60,70,65,125,105,90,4,False

In [82]:
# we can sort through any column for any values using .contains method: the code below shows all Name that contains 'Mega' in it

df.loc[df['Name'].str.contains('Mega')]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
12,9,BlastoiseMega Blastoise,Water,NaN,630,79,103,120,135,115,78,1,False
19,15,BeedrillMega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,579,83,80,80,135,80,121,1,False
71,65,AlakazamMega Alakazam,Psychic,NaN,590,55,50,65,175,95,150,1,False
87,80,SlowbroMega Slowbro,Water,Psychic,590,95,75,180,130,80,30,1,False
102,94,GengarMega Gengar,Ghost,Poison,600,60,65,80,170,95,130,1,False
124,115,KangaskhanMega Kangaskhan,Normal,NaN,590,105,125,100,60,100,100,1,False
137,127,PinsirMega Pinsir,Bug,Flying,600,65,155,120,65,90,105,1,False
141,130,GyaradosMega Gyarados,Water,Dark,640,95,155,109,70,130,81,1,False
154,142,AerodactylMega Aerodactyl,Rock,Flying,615,80,135,85,70,95,150,1,False
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,780,106,190,100,154,100,130,1,True
164,150,MewtwoMega Mewtwo Y,Psychic,NaN,780,106,150,70,194,120,140,1,True
168,154,Meganium,Grass,NaN,525,80,82,100,83,100,80,2,False
196,181,AmpharosMega Ampharos,Electric,Dragon,610,90,95,105,165,110,45,2,False
224,208,SteelixMega Steelix,Steel,Ground,610,75,125,230,55,95,30,2,False
229,212,ScizorMega Scizor,Bug,Steel,600,70,150,140,65,100,75,2,False
232,214,HeracrossMega Heracross,Bug,Fighting,600,80,185,115,40,105,75,2,False
248,229,HoundoomMega Houndoom,Dark,Fire,600,75,90,90,140,90,115,2,False
268,248,TyranitarMega Tyranitar,Rock,Dark,700,100,164,150,95,120,71,2,False
275,254,SceptileMega Sceptile,Grass,Dragon,630,70,110,75,145,85,145,3,False
279,257,BlazikenMega Blaziken,Fire,Fighting,630,80,160,80,130,80,100,3,False
283,260,SwampertMega Swampert,Water,Ground,635,100,150,110,95,110,70,3,False
306,282,GardevoirMega Gardevoir,Psychic,Fairy,618,68,85,65,165,135,100,3,False
327,302,SableyeMega Sableye,Dark,Ghost,480,50,85,125,85,115,20,3,False
329,303,MawileMega Mawile,Steel,Fairy,480,50,105,125,55,95,50,3,False
333,306,AggronMega Aggron,Steel,NaN,630,70,140,230,60,80,50,3,False
336,308,MedichamMega Medicham,Fighting,Psychic,510,60,100,85,80,85,100,3,False
339,310,ManectricMega Manectric,Electric,NaN,575,70,75,80,135,80,135,3,False
349,319,SharpedoMega Sharpedo,Water,Dark,560,70,140,70,110,65,105,3,False
354,323,CameruptMega Camerupt,Fire,Ground,560,70,120,100,145,105,20,3,False
366,334,AltariaMega Altaria,Dragon,Fairy,590,75,110,110,110,105,80,3,False
387,354,BanetteMega Banette,Ghost,NaN,555,64,165,75,93,83,75,3,False
393,359,AbsolMega Absol,Dark,NaN,565,65,150,60,115,60,115,3,False
397,362,GlalieMega Glalie,Ice,NaN,580,80,120,80,120,80,100,3,False
409,373,SalamenceMega Salamence,Dragon,Flying,700,95,145,130,120,90,120,3,False
413,376,MetagrossMega Metagross,Steel,Psychic,700,80,145,150,105,110,110,3,False
418,380,LatiasMega Latias,Dragon,Psychic,700,80,100,120,140,150,110,3,True
420,381,LatiosMega Latios,Dragon,Psychic,700,80,130,100,160,120,110,3,True
426,384,RayquazaMega Rayquaza,Dragon,Flying,780,105,180,100,180,100,115,3,True
476,428,LopunnyMega Lopunny,Normal,Fighting,580,65,136,94,54,96,135,4,False
494,445,GarchompMega Garchomp,Dragon,Ground,700,108,170,115,120,95,92,4,False
498,448,LucarioMega Lucario,Fighting,Steel,625,70,145,88,140,70,112,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,594,90,132,105,132,105,30,4,False
527,475,GalladeMega Gallade,Psychic,Fighting,618,68,165,95,65,115,110,4,False
591,531,AudinoMega Audino,Normal,Fairy,545,103,60,126,80,126,50,5,False
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True

In [83]:
# to show those without 'Mega' we add ~ to the code

df.loc[~df['Name'].str.contains('Mega')]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
794,718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [87]:
#to show which Type 1 contains Psychic or Rock

df.loc[df['Type 1'].str.contains('Psychic|Rock')]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
68,63,Abra,Psychic,NaN,310,25,20,15,105,55,90,1,False
69,64,Kadabra,Psychic,NaN,400,40,35,30,120,70,105,1,False
70,65,Alakazam,Psychic,NaN,500,55,50,45,135,95,120,1,False
71,65,AlakazamMega Alakazam,Psychic,NaN,590,55,50,65,175,95,150,1,False
80,74,Geodude,Rock,Ground,300,40,80,100,30,30,20,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
773,703,Carbink,Rock,Fairy,500,50,50,150,50,150,50,6,False
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True

In [89]:
# We can use the RegEx module with the contains method

#import re module
import re

df.loc[df['Type 1'].str.contains('psychic|rock', flags=re.I, regex=True)] 

#note that the column names 'psychic and rock' are not of the title case, thats why flags=re.I was introduced:which means ignore case

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
68,63,Abra,Psychic,NaN,310,25,20,15,105,55,90,1,False
69,64,Kadabra,Psychic,NaN,400,40,35,30,120,70,105,1,False
70,65,Alakazam,Psychic,NaN,500,55,50,45,135,95,120,1,False
71,65,AlakazamMega Alakazam,Psychic,NaN,590,55,50,65,175,95,150,1,False
80,74,Geodude,Rock,Ground,300,40,80,100,30,30,20,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
773,703,Carbink,Rock,Fairy,500,50,50,150,50,150,50,6,False
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True

In [92]:
#we are not resttricted to just whole names only. We can use re to search for more. NOTE: BRUSH UP ON REGULAR EXPRESSIONS
#this code shows data for Names containing 'pi' in it; [a-z]=xters btw a &z; *= zero or more

df.loc[df['Name'].str.contains('pi[a-z]*', flags=re.I, regex=True)]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
13,10,Caterpie,Bug,NaN,195,45,30,35,20,20,45,1,False
20,16,Pidgey,Normal,Flying,251,40,45,40,35,35,56,1,False
21,17,Pidgeotto,Normal,Flying,349,63,60,55,50,50,71,1,False
22,18,Pidgeot,Normal,Flying,479,83,80,75,70,70,101,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,579,83,80,80,135,80,121,1,False
30,25,Pikachu,Electric,NaN,320,35,55,40,50,50,90,1,False
42,37,Vulpix,Fire,NaN,299,38,41,40,50,65,65,1,False
76,70,Weepinbell,Grass,Poison,390,65,90,50,85,45,55,1,False
84,78,Rapidash,Fire,NaN,500,65,100,70,80,80,105,1,False
136,127,Pinsir,Bug,NaN,500,65,125,100,55,70,85,1,False
137,127,PinsirMega Pinsir,Bug,Flying,600,65,155,120,65,90,105,1,False
181,167,Spinarak,Bug,Poison,250,40,60,40,40,40,30,2,False
186,172,Pichu,Electric,NaN,205,20,40,15,35,35,60,2,False
189,175,Togepi,Fairy,NaN,245,35,20,65,40,65,20,2,False
202,187,Hoppip,Grass,Flying,250,35,35,40,35,55,50,2,False
219,204,Pineco,Bug,NaN,290,50,65,90,35,35,15,2,False
239,221,Piloswine,Ice,Ground,450,100,100,80,60,60,50,2,False
266,247,Pupitar,Rock,Ground,410,70,84,70,65,70,51,2,False
345,316,Gulpin,Poison,NaN,302,70,43,53,43,53,40,3,False
357,326,Grumpig,Psychic,NaN,470,80,45,65,90,110,80,3,False
358,327,Spinda,Normal,NaN,360,60,60,60,60,60,60,3,False
359,328,Trapinch,Ground,NaN,290,45,100,45,45,45,10,3,False
390,357,Tropius,Grass,Flying,460,99,68,83,72,87,51,3,False
438,393,Piplup,Water,NaN,314,53,51,53,61,56,40,4,False
463,416,Vespiquen,Bug,Flying,474,70,80,102,80,102,40,4,False
488,440,Happiny,Normal,NaN,220,100,5,5,15,65,30,4,False
490,442,Spiritomb,Ghost,Dark,485,50,92,108,92,108,35,4,False
501,451,Skorupi,Poison,Bug,330,40,50,90,30,55,65,4,False
502,452,Drapion,Poison,Dark,500,70,90,110,60,75,95,4,False
557,498,Tepig,Fire,NaN,308,65,63,45,45,45,45,5,False
558,499,Pignite,Fire,Fighting,418,90,93,55,70,55,55,5,False
578,519,Pidove,Normal,Flying,264,50,55,50,36,30,43,5,False
596,536,Palpitoad,Water,Ground,384,75,65,55,65,55,69,5,False
716,648,MeloettaPirouette Forme,Normal,Fighting,600,100,128,90,77,77,128,5,False
718,650,Chespin,Grass,NaN,313,56,61,65,48,45,38,6,False

In [93]:
# for Names starting with 'Pi' we add ^

df.loc[df['Name'].str.contains('^pi[a-z]*', flags=re.I, regex=True)]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
20,16,Pidgey,Normal,Flying,251,40,45,40,35,35,56,1,False
21,17,Pidgeotto,Normal,Flying,349,63,60,55,50,50,71,1,False
22,18,Pidgeot,Normal,Flying,479,83,80,75,70,70,101,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,579,83,80,80,135,80,121,1,False
30,25,Pikachu,Electric,NaN,320,35,55,40,50,50,90,1,False
136,127,Pinsir,Bug,NaN,500,65,125,100,55,70,85,1,False
137,127,PinsirMega Pinsir,Bug,Flying,600,65,155,120,65,90,105,1,False
186,172,Pichu,Electric,NaN,205,20,40,15,35,35,60,2,False
219,204,Pineco,Bug,NaN,290,50,65,90,35,35,15,2,False
239,221,Piloswine,Ice,Ground,450,100,100,80,60,60,50,2,False
438,393,Piplup,Water,NaN,314,53,51,53,61,56,40,4,False
558,499,Pignite,Fire,Fighting,418,90,93,55,70,55,55,5,False
578,519,Pidove,Normal,Flying,264,50,55,50,36,30,43,5,False

In [99]:
# for Names starting with p and ending with o

df.loc[df['Name'].str.contains('^p.*o$', flags=re.I, regex=True)]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
21,17,Pidgeotto,Normal,Flying,349,63,60,55,50,50,71,1,False
219,204,Pineco,Bug,NaN,290,50,65,90,35,35,15,2,False
743,675,Pangoro,Fighting,Dark,495,95,124,78,69,71,58,6,False

In [101]:
#for names ending with pi

df.loc[df['Name'].str.contains('pi$', flags=re.I, regex=True)]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
189,175,Togepi,Fairy,NaN,245,35,20,65,40,65,20,2,False
501,451,Skorupi,Poison,Bug,330,40,50,90,30,55,65,4,False

## Conditional changes

In [107]:
#we might want to make specific changes to our data: for instance- change all the fire in Type 1 to flames

df.loc[df['Type 1'] == 'Fire', 'Type 1'] = 'Flames'
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Flames,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Flames,Water,600,80,110,120,130,90,70,6,True

In [108]:
#let's change this back

df.loc[df['Type 1'] == 'Flames', 'Type 1'] = 'Fire'

In [109]:
#you can manipulate in all sort of ways

df.loc[df['Type 1'] == 'Fire', 'Legendary'] = 'Flames']
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,Flames
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,Flames

In [111]:
#for all total greater than 600, genr and legend = 'flames'

df.loc[df['Total'] > 600, ['Generation', 'Legendary']] = 'Flames' #or  = ['Flames', 'Fiery'
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,Flames,Flames
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,Flames
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,Flames,Flames
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,Flames,Flames
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,Flames

## Aggregate Statistics (Groupby)

In [122]:
#lets use our modified file since we've messed the original up. Groupby can give us aggregate stats details like mean, sum, count
#to see the mean of all Type 1 data

df = pd.read_csv('updated pokemon.csv')

df.groupby(['Type 1']).mean()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,,
Bug,334.492754,378.927536,56.884058,70.971014,70.724638,53.869565,64.797101,61.681159,3.217391,0.000000
Dark,461.354839,445.741935,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290,4.032258,0.064516
Dragon,474.375000,550.531250,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250,3.875000,0.375000
Electric,363.500000,443.409091,59.795455,69.090909,66.295455,90.022727,73.704545,84.500000,3.272727,0.090909
Fairy,449.529412,413.176471,74.117647,61.529412,65.705882,78.529412,84.705882,48.588235,4.117647,0.058824
Fighting,363.851852,416.444444,69.851852,96.777778,65.925926,53.111111,64.703704,66.074074,3.370370,0.000000
Fire,327.403846,458.076923,69.903846,84.769231,67.769231,88.980769,72.211538,74.442308,3.211538,0.096154
Flying,677.750000,485.000000,70.750000,78.750000,66.250000,94.250000,72.500000,102.500000,5.500000,0.500000
Ghost,486.500000,439.562500,64.437500,73.781250,81.187500,79.343750,76.468750,64.343750,4.187500,0.062500
Grass,344.871429,421.142857,67.271429,73.214286,70.800000,77.500000,70.428571,61.928571,3.357143,0.042857
Ground,356.281250,437.500000,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250,3.156250,0.125000
Ice,423.541667,433.458333,72.000000,72.750000,71.416667,77.541667,76.291667,63.458333,3.541667,0.083333
Normal,319.173469,401.683673,77.275510,73.469388,59.846939,55.816327,63.724490,71.551020,3.051020,0.020408
Poison,251.785714,399.142857,67.250000,74.678571,68.821429,60.428571,64.392857,63.571429,2.535714,0.000000
Psychic,380.807018,475.947368,70.631579,71.456140,67.684211,98.403509,86.280702,81.491228,3.385965,0.245614
Rock,392.727273,453.750000,65.363636,92.863636,100.795455,63.340909,75.477273,55.909091,3.454545,0.090909
Steel,442.851852,487.703704,65.222222,92.703704,126.370370,67.518519,80.629630,55.259259,3.851852,0.148148
Water,303.089286,430.455357,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286,2.857143,0.035714

In [113]:
#you can sort

df.groupby(['Type 1']).mean().sort_values('Defense', ascending=False)

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,,
Steel,442.851852,487.703704,65.222222,92.703704,126.370370,67.518519,80.629630,55.259259,3.851852,0.148148
Rock,392.727273,453.750000,65.363636,92.863636,100.795455,63.340909,75.477273,55.909091,3.454545,0.090909
Dragon,474.375000,550.531250,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250,3.875000,0.375000
Ground,356.281250,437.500000,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250,3.156250,0.125000
Ghost,486.500000,439.562500,64.437500,73.781250,81.187500,79.343750,76.468750,64.343750,4.187500,0.062500
Water,303.089286,430.455357,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286,2.857143,0.035714
Ice,423.541667,433.458333,72.000000,72.750000,71.416667,77.541667,76.291667,63.458333,3.541667,0.083333
Grass,344.871429,421.142857,67.271429,73.214286,70.800000,77.500000,70.428571,61.928571,3.357143,0.042857
Bug,334.492754,378.927536,56.884058,70.971014,70.724638,53.869565,64.797101,61.681159,3.217391,0.000000
Dark,461.354839,445.741935,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290,4.032258,0.064516
Poison,251.785714,399.142857,67.250000,74.678571,68.821429,60.428571,64.392857,63.571429,2.535714,0.000000
Fire,327.403846,458.076923,69.903846,84.769231,67.769231,88.980769,72.211538,74.442308,3.211538,0.096154
Psychic,380.807018,475.947368,70.631579,71.456140,67.684211,98.403509,86.280702,81.491228,3.385965,0.245614
Electric,363.500000,443.409091,59.795455,69.090909,66.295455,90.022727,73.704545,84.500000,3.272727,0.090909
Flying,677.750000,485.000000,70.750000,78.750000,66.250000,94.250000,72.500000,102.500000,5.500000,0.500000
Fighting,363.851852,416.444444,69.851852,96.777778,65.925926,53.111111,64.703704,66.074074,3.370370,0.000000
Fairy,449.529412,413.176471,74.117647,61.529412,65.705882,78.529412,84.705882,48.588235,4.117647,0.058824
Normal,319.173469,401.683673,77.275510,73.469388,59.846939,55.816327,63.724490,71.551020,3.051020,0.020408

In [114]:
#you can sum

df.groupby(['Type 1']).sum()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,,
Bug,23080,26146,3925,4897,4880,3717,4471,4256,222,0.0
Dark,14302,13818,2071,2740,2177,2314,2155,2361,125,2.0
Dragon,15180,17617,2666,3588,2764,3099,2843,2657,124,12.0
Electric,15994,19510,2631,3040,2917,3961,3243,3718,144,4.0
Fairy,7642,7024,1260,1046,1117,1335,1440,826,70,1.0
Fighting,9824,11244,1886,2613,1780,1434,1747,1784,91,0.0
Fire,17025,23820,3635,4408,3524,4627,3755,3871,167,5.0
Flying,2711,1940,283,315,265,377,290,410,22,2.0
Ghost,15568,14066,2062,2361,2598,2539,2447,2059,134,2.0
Grass,24141,29480,4709,5125,4956,5425,4930,4335,235,3.0
Ground,11401,14000,2361,3064,2715,1807,2008,2045,101,4.0
Ice,10165,10403,1728,1746,1714,1861,1831,1523,85,2.0
Normal,31279,39365,7573,7200,5865,5470,6245,7012,299,2.0
Poison,7050,11176,1883,2091,1927,1692,1803,1780,71,0.0
Psychic,21706,27129,4026,4073,3858,5609,4918,4645,193,14.0
Rock,17280,19965,2876,4086,4435,2787,3321,2460,152,4.0
Steel,11957,13168,1761,2503,3412,1823,2177,1492,104,4.0
Water,33946,48211,8071,8305,8170,8379,7898,7388,320,4.0

In [116]:
#you can count too: for instance to count the number of values in Type 1, we can create a column count and use it

df['count'] = 1

df.groupby(['Type 1']).count()['count']

Type 1
Bug          69
Dark         31
Dragon       32
Electric     44
Fairy        17
Fighting     27
Fire         52
Flying        4
Ghost        32
Grass        70
Ground       32
Ice          24
Normal       98
Poison       28
Psychic      57
Rock         44
Steel        27
Water       112
Name: count, dtype: int64

In [119]:
#you can further count by relating to another column

df.groupby(['Type 1', 'Type 2']).count()['count']

Type 1  Type 2
Bug     Electric     2
        Fighting     2
        Fire         2
        Flying      14
        Ghost        1
                    ..
Water   Ice          3
        Poison       3
        Psychic      5
        Rock         4
        Steel        1
Name: count, Length: 136, dtype: int64

## Working with large amounts of data

In [131]:
#We can load heavy files in to data frames in chunks using the chunksize args
chunk = 1
for df in pd.read_csv('updated pokemon.csv', chunksize=100):
    print('\nchunk', chunk)
    print(df)
    chunk += 1

chunk 1
     #                   Name  Type 1  Type 2  Total   HP  Attack  Defense  \
0    1              Bulbasaur   Grass  Poison    318   45      49       49
1    2                Ivysaur   Grass  Poison    405   60      62       63
2    3               Venusaur   Grass  Poison    525   80      82       83
3    3  VenusaurMega Venusaur   Grass  Poison    625   80     100      123
4    4             Charmander    Fire     NaN    309   39      52       43
..  ..                    ...     ...     ...    ...  ...     ...      ...
95  88                 Grimer  Poison     NaN    325   80      80       50
96  89                    Muk  Poison     NaN    500  105     105       75
97  90               Shellder   Water     NaN    305   30      65      100
98  91               Cloyster   Water     Ice    525   50      95      180
99  92                 Gastly   Ghost  Poison    310   30      35       30

    Sp. Atk  Sp. Def  Speed  Generation  Legendary
0        65       65     45           1      False
1        80       80     60           1      False
2       100      100     80           1      False
3       122      120     80           1      False
4        60       50     65           1      False
..      ...      ...    ...         ...        ...
95       40       50     25           1      False
96       65      100     50           1      False
97       45       25     40           1      False
98       85       45     70           1      False
99      100       35     80           1      False

[100 rows x 13 columns]

chunk 2
       #                   Name    Type 1  Type 2  Total   HP  Attack  \
100   93                Haunter     Ghost  Poison    405   45      50
101   94                 Gengar     Ghost  Poison    500   60      65
102   94      GengarMega Gengar     Ghost  Poison    600   60      65
103   95                   Onix      Rock  Ground    385   35      45
104   96                Drowzee   Psychic     NaN    328   60      48
..   ...                    ...       ...     ...    ...  ...     ...
195  181               Ampharos  Electric     NaN    510   90      75
196  181  AmpharosMega Ampharos  Electric  Dragon    610   90      95
197  182              Bellossom     Grass     NaN    490   75      80
198  183                 Marill     Water   Fairy    250   70      20
199  184              Azumarill     Water   Fairy    420  100      50

     Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary
100       45      115       55     95           1      False
101       60      130       75    110           1      False
102       80      170       95    130           1      False
103      160       30       45     70           1      False
104       45       43       90     42           1      False
..       ...      ...      ...    ...         ...        ...
195       85      115       90     55           2      False
196      105      165      110     45           2      False
197       95       90      100     50           2      False
198       50       20       50     40           2      False
199       80       60       80     50           2      False

[100 rows x 13 columns]

chunk 3
       #       Name  Type 1  Type 2  Total  HP  Attack  Defense  Sp. Atk  \
200  185  Sudowoodo    Rock     NaN    410  70     100      115       30
201  186   Politoed   Water     NaN    500  90      75       75       90
202  187     Hoppip   Grass  Flying    250  35      35       40       35
203  188   Skiploom   Grass  Flying    340  55      45       50       45
204  189   Jumpluff   Grass  Flying    460  75      55       70       55
..   ...        ...     ...     ...    ...  ..     ...      ...      ...
295  272   Ludicolo   Water   Grass    480  80      70       70       90
296  273     Seedot   Grass     NaN    220  40      40       50       30
297  274    Nuzleaf   Grass    Dark    340  70      70       40       60
298  275    Shiftry   Grass    Dark    480  90     100       60       90
299  276    Taillow  Normal  Flying    270  40      55       30       30

     Sp. Def  Speed  Generation  Legendary
200       65     30           2      False
201      100     70           2      False
202       55     50           2      False
203       65     80           2      False
204       95    110           2      False
..       ...    ...         ...        ...
295      100     70           3      False
296       30     30           3      False
297       40     60           3      False
298       60     80           3      False
299       30     85           3      False

[100 rows x 13 columns]

chunk 4
       #               Name   Type 1  Type 2  Total  HP  Attack  Defense  \
300  277            Swellow   Normal  Flying    430  60      85       60
301  278            Wingull    Water  Flying    270  40      30       30
302  279           Pelipper    Water  Flying    430  60      50      100
303  280              Ralts  Psychic   Fairy    198  28      25       25
304  281             Kirlia  Psychic   Fairy    278  38      35       35
..   ...                ...      ...     ...    ...  ..     ...      ...
395  361            Snorunt      Ice     NaN    300  50      50       50
396  362             Glalie      Ice     NaN    480  80      80       80
397  362  GlalieMega Glalie      Ice     NaN    580  80     120       80
398  363             Spheal      Ice   Water    290  70      40       50
399  364             Sealeo      Ice   Water    410  90      60       70

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
300       50       50    125           3      False
301       55       30     85           3      False
302       85       70     65           3      False
303       45       35     40           3      False
304       65       55     50           3      False
..       ...      ...    ...         ...        ...
395       50       50     50           3      False
396       80       80     80           3      False
397      120       80    100           3      False
398       55       50     25           3      False
399       75       70     45           3      False

[100 rows x 13 columns]

chunk 5
       #                 Name    Type 1 Type 2  Total   HP  Attack  Defense  \
400  365              Walrein       Ice  Water    530  110      80       90
401  366             Clamperl     Water    NaN    345   35      64       85
402  367              Huntail     Water    NaN    485   55     104      105
403  368             Gorebyss     Water    NaN    485   55      84      105
404  369            Relicanth     Water   Rock    485  100      90      130
..   ...                  ...       ...    ...    ...  ...     ...      ...
495  446             Munchlax    Normal    NaN    390  135      85       40
496  447                Riolu  Fighting    NaN    285   40      70       40
497  448              Lucario  Fighting  Steel    525   70     110       70
498  448  LucarioMega Lucario  Fighting  Steel    625   70     145       88
499  449           Hippopotas    Ground    NaN    330   68      72       78

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
400       95       90     65           3      False
401       74       55     32           3      False
402       94       75     52           3      False
403      114       75     52           3      False
404       45       65     55           3      False
..       ...      ...    ...         ...        ...
495       40       85      5           4      False
496       35       40     60           4      False
497      115       70     90           4      False
498      140       70    112           4      False
499       38       42     32           4      False

[100 rows x 13 columns]

chunk 6
       #        Name    Type 1    Type 2  Total   HP  Attack  Defense  \
500  450   Hippowdon    Ground       NaN    525  108     112      118
501  451     Skorupi    Poison       Bug    330   40      50       90
502  452     Drapion    Poison      Dark    500   70      90      110
503  453    Croagunk    Poison  Fighting    300   48      61       40
504  454   Toxicroak    Poison  Fighting    490   83     106       65
..   ...         ...       ...       ...    ...  ...     ...      ...
595  535     Tympole     Water       NaN    294   50      50       40
596  536   Palpitoad     Water    Ground    384   75      65       55
597  537  Seismitoad     Water    Ground    509  105      95       75
598  538       Throh  Fighting       NaN    465  120     100       85
599  539        Sawk  Fighting       NaN    465   75     125       75

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
500       68       72     47           4      False
501       30       55     65           4      False
502       60       75     95           4      False
503       61       40     50           4      False
504       86       65     85           4      False
..       ...      ...    ...         ...        ...
595       50       40     64           5      False
596       65       55     69           5      False
597       85       75     74           5      False
598       30       85     45           5      False
599       30       75     85           5      False

[100 rows x 13 columns]

chunk 7
       #        Name Type 1    Type 2  Total  HP  Attack  Defense  Sp. Atk  \
600  540    Sewaddle    Bug     Grass    310  45      53       70       40
601  541    Swadloon    Bug     Grass    380  55      63       90       50
602  542    Leavanny    Bug     Grass    500  75     103       80       70
603  543    Venipede    Bug    Poison    260  30      45       59       30
604  544  Whirlipede    Bug    Poison    360  40      55       99       40
..   ...         ...    ...       ...    ...  ..     ...      ...      ...
695  634    Zweilous   Dark    Dragon    420  72      85       70       65
696  635   Hydreigon   Dark    Dragon    600  92     105       90      125
697  636    Larvesta    Bug      Fire    360  55      85       55       50
698  637   Volcarona    Bug      Fire    550  85      60       65      135
699  638    Cobalion  Steel  Fighting    580  91      90      129       90

     Sp. Def  Speed  Generation  Legendary
600       60     42           5      False
601       80     42           5      False
602       80     92           5      False
603       39     57           5      False
604       79     47           5      False
..       ...    ...         ...        ...
695       70     58           5      False
696       90     98           5      False
697       55     60           5      False
698      105    100           5      False
699       72    108           5       True

[100 rows x 13 columns]

chunk 8
       #                      Name    Type 1    Type 2  Total  HP  Attack  \
700  639                 Terrakion      Rock  Fighting    580  91     129
701  640                  Virizion     Grass  Fighting    580  91      90
702  641   TornadusIncarnate Forme    Flying       NaN    580  79     115
703  641     TornadusTherian Forme    Flying       NaN    580  79     100
704  642  ThundurusIncarnate Forme  Electric    Flying    580  79     115
..   ...                       ...       ...       ...    ...  ..     ...
795  719                   Diancie      Rock     Fairy    600  50     100
796  719       DiancieMega Diancie      Rock     Fairy    700  50     160
797  720       HoopaHoopa Confined   Psychic     Ghost    600  80     110
798  720        HoopaHoopa Unbound   Psychic      Dark    680  80     160
799  721                 Volcanion      Fire     Water    600  80     110

     Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary
700       90       72       90    108           5       True
701       72       90      129    108           5       True
702       70      125       80    111           5       True
703       80      110       90    121           5       True
704       70      125       80    111           5       True
..       ...      ...      ...    ...         ...        ...
795      150      100      150     50           6       True
796      110      160      110    110           6       True
797       60      150      130     70           6       True
798       60      170      130     80           6       True
799      120      130       90     70           6       True

[100 rows x 13 columns]

Note: This note was inspired from Keith Galli's Tutorial on Pandas.